apiVersion: v1
data:
  token: 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
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    version: {{ .Chart.AppVersion }}