# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false

image:
  repository: xevis
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.5-fa7aaf3"
  arch: amd64
  os: linux

secret:
  name: "TELE_TOKEN"
  tokenKey: "token"
  tokenName: "kobot"
securityContext:
  privilegent: true
service:
  port: 80