# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
autoscaling:
  enabled: false
ingress:
  enabled: false
image:
  repository: "${{ Igor-Kostyrenko | lower }}"
  registry: ""
  # pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

  tag: "v1.0.8-1c75f58"
  arch: ""
  os: ""
secret:
  name: "TELE_TOKEN"
  tokenKey: "token"
  tokenName: "kobot"
securityContext:
  privilegent: true
service:
  port: 80
