name: KOBOT-CICD
 
on: 
  push:
    branches: [main, develop]

env:
  TARGETOS: linux
  TARGETARCH: amd64

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Run tests
        run: make test

      - name: Build and Push Docker image
        env:
          APP: kobot
          REGISTRY: ghcr.io
          REPOSITORY: ${{ github.repository_owner }}
        run: |
          make build image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Set version
        run: echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update Helm chart
        uses: azure/setup-helm@v1
        with:
          version: v3.6.0

      - name: Update Helm chart version
        run: helm chart save helm kobot
